# Generated by Django 5.0.4 on 2025-02-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('vigente', models.BooleanField(default=True)),
            ],
        ),
    ]
