# Generated by Django 5.0.4 on 2025-02-10 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('aprobado', models.BooleanField(default=False)),
                ('autorizacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autorizaciones.autorizacion')),
            ],
        ),
    ]
