# Generated by Django 5.0.4 on 2025-02-10 02:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0003_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='autorizaciones.municipio')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='autorizaciones.proyecto')),
            ],
        ),
    ]
